// Get All App Records
GET http://localhost:3001/apps

###
// Get Specific App Record
GET http://localhost:3001/apps/5

###
// Add New App Record
POST http://localhost:3001/apps
Content-Type: application/json

{
    "appName": "testApp2",
    "jackpotId": 1,
    "jackpotVersion": "1.0.0.0",
    "region": "Colombia",
    "interface": "ultrahd",
    "gameList": [
        {
            "gameId": 1,
            "gameVersion": ["1.0.0.0", "1"]
        }
    ]
}

###
// Delete Specific App Record
DELETE http://localhost:3001/apps/663cd19a0acf693338d00e41

###
// Delete All Apps
DELETE http://localhost:3001/apps

###
// Update Specific App Record
PATCH http://localhost:3001/apps/1
Content-Type: application/json

{
    "appName": "testApp1",
    "jackpotId": 1,
    "jackpotVersion": ["1.0.0.0", "1"],
    "region": "Latvia",
    "interface": "Interface1",
    "gameId": 1,
    "gameVersion": ["1.0.0.0", "1"]
}