// Get All Game Records
GET http://localhost:3001/games

###
// Get Specific Game Record
GET http://localhost:3001/games/1

###
// Add New Game Record
POST http://localhost:3001/games
Content-Type: application/json

{
    "gameName": "testGame3",
    "systemId": 15,
    "maxWLCMain": 5000,
    "maxWLCFreegames": 10000,
    "freegames": false,
    "gamble": true,
    "jackpot": true,
    "mathId": 1
}

###
// Delete Specific Game Record
DELETE http://localhost:3001/games/3

###
// Delete All Games
DELETE http://localhost:3001/games

###
// Update Specific Game Record
PATCH http://localhost:3001/games/0
Content-Type: application/json

{
    "gameName": "testGame1",
    "systemId": 1,
    "maxWLCMain": 50001,
    "maxWLCFreegames": 10000,
    "freegames": false,
    "gamble": true,
    "jackpot": true,
    "mathId": 1
}