// Get All Math Records
GET http://localhost:3001/maths

###
// Get Specific Math Record
GET http://localhost:3001/maths/2

###
// Add New Math Record
POST http://localhost:3001/maths
Content-Type: application/json

{
    "mathName": "testMath3",
    "percentage": [1, 2],
    "percentageSetList": [1, 2, 3]
}

###
// Delete Specific Math Record
DELETE http://localhost:3001/maths/1
percentage
###
// Delete All Maths
DELETE http://localhost:3001/maths

###
// Update Specific Math Record
PATCH http://localhost:3001/maths/2
Content-Type: application/json

{
    "mathName": "testMath2",
    "percentage": [1, 2],
    "percentageSetList": [1, 2, 3]
}